# api_base_url = "https://api.deepseek.com/v1"
# api_key = "sk-2a1432bca3b648d48e3f3ca13ee9fb7a"
api_base_url = "https://api.siliconflow.cn/v1"
api_key = "sk-fsaryljvbhpbzxndzkuwdmackwyfqzwatljrntinnojeiwmt"
# llm_model = "deepseek-chat"
model = "deepseek-ai/DeepSeek-V2.5"